language: C
os:
        - linux
        - osx
compiler:
        - clang
        - gcc
script: if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then make && make test; else make -f MakefileOSX && make -f MakefileOSX test; fi

