language: C
os:
        - linux
        - osx
compiler:
        - clang
        - gcc

osx_image: xcode12.2

addons:
        homebrew:
                packages:
                        - readline
                        - bison
                update: true
script: if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then make && make test; else make -f MakefileOSX && make -f MakefileOSX test; fi

